appointment/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *


app_name = 'mysites'

urlpatterns = [    
    path('', dashboard, name='dashboard'),   
    path('login/', UserLogin, name="userLogin"),
    path('register/', UserRegister, name="register"),
    path('profile/', GetProfile, name="profile"),
    path('user/status/<int:status>/<int:user_id>', ChangeStatus, name="change-status"),
    path('user/logout/', logout, name="user-logout"),
    path('doctors/', doctorsList, name='doctors-list'),
    path('doctor/<int:doctor_id>', doctorsDetails, name='single-doctor'),
    path('doctor/appointment/<int:doctor_id>/<int:time_id>', doctorsAppoint, name='appointment-doctor'),
    path('my-appointments', myAppointment, name='appointment')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ustech/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appointment.urls')),
]

appointment/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from datetime import date, datetime, time, timedelta
# Create your models here.

class UserModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) 

    class Meta:
        db_table = "users"
        
@receiver(post_save, sender=User)
def create_user_usermodel(sender, instance, created, **kwargs):
    if created:
        UserModel.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_model(sender, instance, **kwargs):
    instance.usermodel.save()



class Doctor(models.Model):
    doctor_name = models.CharField(max_length=128)
    specialist = models.CharField(max_length=512)
    experince = models.CharField(max_length=512)
    charges = models.CharField(max_length=512)
    avatar = models.ImageField()

    def __str__(self):
        return self.doctor_name

times = []
for i in range(0, 24*4):
    times.append((datetime.combine(date.today(), time()) + timedelta(minutes=15) * i).time())
TIMES_SLOT = [("","---------")]+[( choice.strftime("%H:%M:%S"), choice.strftime("%I:%M %p").lstrip('0') ) for choice in times]

class Timings(models.Model):
    slots = models.CharField(max_length=50, unique=True, choices=TIMES_SLOT)

    def __str__(self):
        dt = datetime.strptime(self.slots,"%H:%M:%S")
        return dt.strftime("%I:%M %p")

class DoctorTimeSchedule(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    my_slot = models.ManyToManyField(Timings)

    def slots_time(self):
        return ", ".join([datetime.strptime(a.slots,"%H:%M:%S").strftime("%I:%M %p") for a in self.my_slot.all()])

class MyAppointments(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    doctor_id = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    timing = models.ForeignKey(Timings, on_delete=models.CASCADE)
    


    

appointment/forms.py
from django import forms
from django.forms import ModelForm
from django.db import models
from appointment.models import *
from django.core import validators
from django.contrib.auth.models import User
from django.core.validators import *
from django.core.validators import MaxLengthValidator
from django.core.exceptions import ValidationError


FIELD_NAME_MAPPING = {
    'username': 'uname',    
}
class LoginForm(forms.Form):    
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id' : "inputEmail" ,
                    'placeholder' : 'Enter Email or Username', 'autofocus' : 'autofocus'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'id' : "inputPassword" ,
                     'placeholder' : 'Enter Password', 'autofocus' : 'autofocus'}),validators=[validators.MinLengthValidator(5)])
  

class regForm(forms.Form):    
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id' : "firstName" ,
                    'placeholder' : 'Enter Name', 'autofocus' : 'autofocus'}),validators=[validators.MinLengthValidator(5), validators.MaxLengthValidator(10)])
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id' : "inputEmail" ,
                    'placeholder' : 'Enter Email'}),validators=[validators.validate_email])

    uname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id' : "username" ,
                    'placeholder' : 'Enter Username'}),validators=[validators.MinLengthValidator(5), validators.MaxLengthValidator(8)])
                    
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'id' : "inputPassword" ,
                     'placeholder' : 'Enter Password'}),validators=[validators.MinLengthValidator(5), validators.MaxLengthValidator(8)])

    def clean(self):
        cleaned_data = self.cleaned_data
        email = cleaned_data.get('email')
        uname = cleaned_data.get('uname')

        if User.objects.filter(email=email).exists() == True and User.objects.filter(email=email).exists() == True:            
            # self._errors['email'] 
            raise forms.ValidationError({'email': ["Email is already exist",], 'uname': ["Username is already exist",]})
        
        if User.objects.filter(email=email).exists() == True:            
            # self._errors['email'] 
            raise forms.ValidationError({'email': ["Email is already exist",]})

        if User.objects.filter(username=uname).exists() == True:            
            # self._errors['email'] 
            raise forms.ValidationError({'uname': ["Username is already exist",]})

        return self.cleaned_data

appointment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core import validators
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.validators import EmailValidator
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from appointment.forms import *
from appointment.models import *
from appointment.functions import handle_uploaded_file
from .functions import *
from django.db.models import Q



from django.contrib.auth.hashers import make_password, check_password
# Create your views here.

def dashboard(request):    
    if 'user' in request.session:
        data = User.objects.get(id=request.session['user']['user_id'])
        
        # print(data[0].name)
        context = {
            'data' : data,
        }        
       
        return redirect('/profile/')
    else:
        return redirect("/login/")

def UserLogin(request):

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            var = request.POST.get('email')
            pwd = request.POST.get('password')            
            if '@' in var :         
                check = authenticate(email=var, password=pwd)
                n = 'Email '              
            else:

                check = authenticate(username=var, password=pwd)
                n = 'Username '          
            
            if check and check != None:
                if check_password(pwd,check.password):
                    login(request, check)
                    request.session['user'] = { 'email' : check.email, 'user_id' : check.id }
                   
                    return redirect("/")
                else:
                    messages.error(request, n+" and password is incorrect.")
                    return redirect("/login/")
                    
            else:
                messages.error(request, "User doesn't exist. or you are banned")
                return redirect("/login/")            

    else:
        form = LoginForm()
    context = {
        'form':form
    }

    return render(request, 'login.html', context)

def UserRegister(request):
    if request.method == 'POST':
        form = regForm(request.POST)
        if form.is_valid():            
            password = make_password(request.POST['password'])
            uname = request.POST['uname']
            email = request.POST['email']
            name = request.POST['name']       
            regist = User.objects.create(username=uname, email=email,
                     first_name=name, password=password, is_active=1)  
            
            

            if regist :
                messages.success(request, 'Thank you for register with us')
                return redirect("/login/")
            else :
                messages.error(request, 'Something went wrong.')
                return redirect("/register/")
    else:
        form = regForm()
    context = {
        'form' : form
    }
    return render(request, 'register.html', context)

def GetProfile(request):
    print(request.session)
    if 'user' in request.session :        
        data = User.objects.get(pk=request.session['user']['user_id'])
        context = {
            'data' : data,
            
        }
        return render(request, 'profile.html', context)
    else:
        return redirect("/login/")


        return redirect("/login/")

def ChangeStatus(request, status, user_id=None):
    if 'user' in request.session and user_id != None:
        if request.session['user']['role'] == 'admin':
            data = UserModel.objects.only("user_id","status").get(user_id=user_id)
            if status == 1:
                data.status = 0
            else:
                print(user_id)
                print(status)        
                data.status = 1
            data.save()        
            return redirect("/")
        else:
            return redirect("/login/")
    else:
        return redirect("/login/")

def logout(request):
    request.session.flush()
    return redirect('/login/')

@login_required
def doctorsList(request):
    doctors = Doctor.objects.all()
    return render(request, 'doctors.html', locals())

@login_required
def doctorsDetails(request, doctor_id):
    try:
        doctor = Doctor.objects.get(id=doctor_id)
        doctorTimings = DoctorTimeSchedule.objects.get(doctor=doctor_id)
        timings = doctorTimings.my_slot.all()
    except:
        return redirect('/doctors/')
    return render (request, 'single_doctor.html', locals())

@login_required
def doctorsAppoint(request, doctor_id, time_id):
    try:
        doctor = Doctor.objects.get(id=doctor_id)
        timings = Timings.objects.get(id=time_id)
        appoint = MyAppointments()
        appoint.user_id = request.user
        appoint.doctor_id = doctor
        appoint.timing = timings
        appoint.save()
    except Doctor.DoesNotExist:
        messages.ERROR(request, 'Doctor not valid')
        return redirect('/doctors/')
    except Timings.DoesNotExist:
        messages.ERROR(request, 'Invalid timing')
        return redirect('/doctor/'+str(doctor_id))
    messages.success(request, 'Your Appointment is booked')
    return redirect('/my-appointments')

@login_required
def myAppointment(request):
    
    appointments = MyAppointments.objects.filter(user_id=request.user)
    if not appointments:
        messages.ERROR(request, 'You have no appointment')
        return redirect('/profile')
    return render(request, 'myappointment.html', locals())

appointment/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %} | ustech {% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}"  rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{% static "vendor/datatables/dataTables.bootstrap4.css" %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static "css/sb-admin.css" %}" rel="stylesheet">

</head>

<body id="page-top">

  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html">ustech</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
       
        <div class="input-group-append">
          
        </div>
      </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        {% comment %} <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a> {% endcomment %}
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      {% comment %} <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a> {% endcomment %}
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          {% comment %} <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Activity Log</a> {% endcomment %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'mysites:user-logout' %}" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item active">
      
       {% if role == 'admin'%}
        <a class="nav-link" href="/">
        {% else %}
          <a class="nav-link" href="/profile/">
        {% endif %}
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item ">
         <a class="nav-link "  href="/doctors" id="" >
          <i class="fas fa-fw fa-folder"></i>
          <span>Doctors</span>
        </a> 
        
      </li>
      <li class="nav-item ">
        <a class="nav-link "  href="/my-appointments" id="" >
         <i class="fas fa-fw fa-folder"></i>
         <span>My Appointments</span>
       </a> 
       
     </li>
      <li class="nav-item">
        <a class="nav-link">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>{{ data.first_name|title }}</span></a>
      </li>
      <li class="nav-item">
      {% if role == 'admin' %}
       <a class="nav-link" href="/profile/">
          <i class="fas fa-fw fa-table"></i>
          <span>Profile</span></a>
      </li> 
      {% endif %}
    </ul>

    <div id="content-wrapper">
        {% block content %}
        {% endblock %}
      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Your Website 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="/user/logout/">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{% static "vendor/chart.js/Chart.min.js" %}"></script>
  <script src="{% static "vendor/datatables/jquery.dataTables.js" %}"></script>
  <script src="{% static "vendor/datatables/dataTables.bootstrap4.js" %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static "js/sb-admin.min.js" %}"></script>

  <!-- Demo scripts for this page-->
  <script src="{% static "js/demo/datatables-demo.js" %}"></script>
    
  <script>
    $("#profile_pic-clear_id").next().text("")
  </script>

</body>

</html>

appointment/templates/baseE.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Lyxel | {% block title %}  {% endblock title %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template-->
  <link href="{% static "css/sb-admin.css" %}" rel="stylesheet">

</head>

<body class="bg-dark">
    {% block loginContent %}
    {% endblock loginContent %}
  <!-- Bootstrap core JavaScript-->
  <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>

</body>

</html>

appointment/templates/doctors.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %} Doctors {% endblock title %}
{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static '/css/custom.css' %}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Doctors</li>
</ol>

<!-- Page Content -->
<div class="container">
    <div class="row">
        <h2>Doctors List</h2>
    </div>
</div>
<div class="carousel-reviews broun-block">
    <div class="container">
        <div class="row">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}
                    </li>
                    {% endfor %}
            </ul>
            {% endif %}
            <div id="carousel-reviews" class="carousel slide" data-ride="carousel">

                <div class="carousel-inner">
                    {% for doct in doctors %}

                    <div class="item {% if forloop.counter == 1 %}active{% endif %}">
                        <div class="col-md-4 col-sm-6">
                            <div class="block-text rel zmin">
                                <a title="" href="#">{{ doct.specialist }}</a>

                                <p> Experince : {{ doct.experince }}
                                    Charges: {{ doct.charges }}</p>
                                <ins class="ab zmin sprite sprite-i-triangle block"></ins>
                            </div>
                            <div class="person-text rel">
                                <img src="/media/{{ doct.avatar }}" width="100" height="100" />
                                <a title="" href="/doctor/{{ doct.id }}">{{ doct.doctor_name }}</a>

                            </div>
                        </div>

                    </div>
                    {% endfor %}
                </div>
                <a class="left carousel-control" href="#carousel-reviews" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-reviews" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

appointment/templates/login.html
{% extends 'baseE.html' %}
{% load static %}
{% block title %} Login {% endblock title %}
{% block loginContent %}
  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Login</div>
      <div class="card-body">
      <!-- validation messsage -->
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <!-- end message -->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <form method="post" action="/login/">
        {% csrf_token %}
          <div class="form-group">
            <div class="form-label-group">
                {{ form.email }}              
              <label for="inputEmail">Enter Email or Username</label>
              
            </div>
          </div>
          <div class="form-group">
            <div class="form-label-group">            
              {{ form.password }}
              <label for="inputPassword">Password</label>
            </div>
          </div>          
          <input type="submit" class="btn btn-primary btn-block" value="Login" name="Login" />
          
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="/register">Register an Account</a>
          {# <a class="d-block small" href="forgot-password.html">Forgot Password?</a> #}
        </div>
      </div>
    </div>
  </div>

{% endblock %}

appointment/templates/myappointment.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Appointments {% endblock title %}
{% block content %}
<div class="container-fluid">

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
    <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Appointments</li>
</ol>

<!-- Icon Cards-->




<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
    <i class="fas fa-table"></i>
    My Appointments</div>
    <div class="card-body">
    <div class="table-responsive">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
            <th>Doctor Name</th>
            <th>Specialist</th>
            <th>Charges</th>
            <th>Timings</th>
            
            </tr>
        </thead>
        
        <tbody>
            {% for appoint in appointments %}
            <tr>
            
            <td>{{ appoint.doctor_id.doctor_name|title }}</td>
            <td>{{ appoint.doctor_id.specialist }}</td>
            <td>{{ appoint.doctor_id.charges }}</td>
            <td>{{ appoint.timing }}</td>            
            
            </tr>      
            {% endfor %}      
        </tbody>
        </table>
    </div>
    </div>
    <div class="card-footer small text-muted">Today {% now "jS F Y H:i" %}</div>
</div>

</div>
<!-- /.container-fluid -->
{% endblock %}

appointment/templates/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %} Profile {% endblock title %}
{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static '/css/custom.css' %}">
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Profile</li>
</ol>

<!-- Page Content -->
<div class="container">
    <div class="row">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <div class="col-sm-4 col-md-4">

        </div>
        
        <div class="col-sm-2 col-md-4">                
                <!-- {% cycle 'odd' 'even' %}
                {{ value|default:"nothing" }}
                {% trans "This is the title" as the_title %} -->                
            <blockquote class="blockquote">                        
                <p class="mb-0">{{ data.first_name|title }}</p> <small> <i class="glyphicon glyphicon-map-marker"></i></small>
            </blockquote>
            <p class="lead"> <i class="fa fa-envelope"></i> {{ data.email }}                
                <br /> <i class="fa fa-user"></i> {{ data.username }}
                <br /> <i class="fa fa-clock"></i> {{ data.created_at }}</p>
                
        </div>
    </div>
</div>
{% endblock content %}

appointment/templates/register.html
{% extends 'baseE.html' %}
{% load static %}
{% block title %} Register {% endblock title %}
{% block loginContent %}

<div class="container">
    <div class="card card-register mx-auto mt-5">
        <div class="card-header">Register an Account</div>
        <div class="card-body">                        
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
       
        <form method="POST" action="/register/">
            {% csrf_token %}
            <div class="form-group">
            <div class="form-row">
                <div class="col-md-12">
                <div class="form-label-group">
                    {{ form.name }}                    
                    <label for="firstName">Name</label>                    
                    {{ form.name.errors|escape }}                    
                </div>
                </div>             
            </div>
            </div>
            <div class="form-group">
            <div class="form-label-group">
                {{ form.email }}
                <label for="inputEmail">Email address</label>
                {{ form.email.errors|escape }} 
            </div>
            </div>
            <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                <div class="form-label-group">
                    {{ form.uname }}
                    <label for="username">Username</label>
                    {{ form.uname.errors|escape }} 
                </div>
                </div>
                <div class="col-md-6">
                <div class="form-label-group">
                    {{ form.password }}                    
                    <label for="inputPassword">password</label>
                    {{ form.password.errors|escape }} 
                </div>
                </div>
            </div>
            </div>
            <input type="submit" class="btn btn-primary btn-block" value="Register" />
        </form>
        <div class="text-center">
            <a class="d-block small mt-3" href="/login">Login Page</a>
            {# <a class="d-block small" href="forgot-password.html">Forgot Password?</a> #}
        </div>
        </div>
    </div>
</div>
{% endblock %}